---
title: John Ellis Photography
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: john@seriouslyawesome.com
description: The photography of John Ellis. Located near Austin, Texas.
baseurl:
url:
github_username: SeriouslyAwesome
theme: minima
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"